name: Bug Report
description: Please do not use bug reports for support issues or feature requests.
labels: ['status:not-yet-viewed', 'bug']
assignees: 'meisnate12'

body:
  - type: markdown
    attributes:
      value: >
        **THIS IS NOT THE PLACE TO ASK FOR SUPPORT!**
        Please use [Plex Meta Manager Discord](https://discord.gg/NfH6mGFuAB) and post your question under the `pmm-help` channel for support issues.
  - type: input
    id: version
    attributes:
      label: Version Number
      description: Can be found at the beginning of your log file
      placeholder: eg. 1.1.0
    validations:
      required: true
  - type: dropdown
    id: branch
    attributes:
      label: What branch are you on?
      options:
        - master
        - develop
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Logs
      description: >
        Please share the relevant log file with the error on [Gist](https://gist.github.com).
      placeholder: "https://gist.github.com"