name: Docker Develop Release

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  docker-develop:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: meisnate12
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            "BRANCH_NAME=develop"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: meisnate12/${{ secrets.DOCKER_REPO }}:develop

      - name: Send Discord Commit Notification
        uses: meisnate12/discord-notifications@master
        with:
          webhook_id_token: ${{ secrets.DEVELOP_WEBHOOK }}
          title: ${{ secrets.NAME }} Develop Commits
          message: "${{ secrets.DEVELOP_TAG }} - An update to ${{ secrets.NAME }} has been published and is available to users of the **develop** branch."
          commits: "true"
          username: Metabot
          avatar_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/develop/.github/pmm.png

      - name: Discord Success Notification
        uses: meisnate12/discord-notifications@master
        if: success()
        with:
          webhook_id_token: ${{ secrets.BUILD_WEBHOOK }}
          title: "develop build: **Success**"
          url: https://github.com/meisnate12/${{ secrets.GITHUB }}/actions/runs/${{ github.run_id }}
          username: Metabot
          avatar_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/develop/.github/pmm.png
          author: ${{ secrets.NAME }} Docker
          author_icon_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/develop/.github/docker.png

      - name: Discord Failure Notification
        uses: meisnate12/discord-notifications@master
        if: failure()
        with:
          webhook_id_token: ${{ secrets.BUILD_WEBHOOK }}
          message: <@&1079153184007790652>
          title: "develop build: **Failure**"
          color: 0xe30c43
          url: https://github.com/meisnate12/${{ secrets.GITHUB }}/actions/runs/${{ github.run_id }}
          username: Metabot
          avatar_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/develop/.github/pmm.png
          author: ${{ secrets.NAME }} Docker
          author_icon_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/develop/.github/docker.png
