name: Release

on:
  release:
    types: [ published ]

jobs:

  release-notification:

    runs-on: ubuntu-latest
    steps:

      - name: Send Discord Release Notification
        uses: meisnate12/discord-notifications@master
        with:
          webhook_id_token: ${{ secrets.RELEASE_WEBHOOK }}
          release: true
          title: ${{ secrets.NAME }} Release VERSION
          message: "${{ secrets.RELEASE_TAG }} - A new version of ${{ secrets.NAME }} has been released and is available to all users"
          username: Metabot
          avatar_url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/.github/pmm.png